version: "3"
services:
  api:
    build: 
      context: ./
      dockerfile: local.dockerfile
      args:
        port: ${PORT}
    environment:
      - 'GOOGLE_APPLICATION_CREDENTIALS=${FIREBASE_CREDENTIALS}'
    image: xanderza/oumienet-local-api:latest
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - redis
    volumes:
      - /var/www/oumienet/web-api:/usr/src/oumienet-api
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 128M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - /home/docker/mysql:/var/lib/mysql
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - /home/docker/data:/data
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet: